name: 'Dotnet Affected'
description: 'Runs dotnet-affected'
author: 'Leonardo Chaia (me@leonardochaia.com)'
branding:
  icon: 'layers'  
  color: 'green'
inputs:
  toolVersion:
    description: 'dotnet-affected version to install'
  from:
    description: 'Commit/branch/revision for git diff'
  to:
    description: 'Commit/branch/revision for git diff'
  exclude:
    description: 'Valid .Net Regex pattern to ignore from build'
  solution-path:
    description: 'Path to a Solution file (.sln) used to discover projects that may be affected.'
  output-format:
    description: 'Space separated list of formats to use. (i.e text traversal)'
outputs:
  affected:
    description: The list of changed and affected projects, if any
runs:
  using: 'node16'
  main: 'dist/index.js'
